[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
zircuit = "${NETWORK_URL}"

[etherscan]
zircuit = { key = "${API_KEY}", chain = 48898, url = "${VERIFICATION_URL}" }


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
